### ISSUE TITLE
Masto account feed not detected

### ISSUE THREAD

**Issue by sneakers-the-rat** [gugray/rss-parrot#15]
Tried to follow myself: https://neuromatch.social/@jonny/111709784531341231
got this error message: https://rss-parrot.net/u/birb/status/1704442136821027061

it seems like this was the one i was supposed to get, right?:
https://github.com/gugray/rss-parrot/blob/4d150e8dd4cfabed7beea5f1d89fe4efd1c2f805/src/server/logic/inbox.go#L343

something not working right in that "get account for feed" function or the control flow in there :)

cool thing!!! nice work!
edit: sorry that reads as sarcastic, i meant it sincerely

**Comment by gugray** [comment]
Yup, that control flow was borked lol. I direly need to improve the testing situation of this code; I skimped on that very unprofessionally.

The intended behavior is to NOT relay RSS feeds from Mastodon, and to send a meaningful reply about that to the asker. The reason being partly technical (this could trigger endless relay loops), and partly moral: this could be used to circumvent instance blocks, which I don't want to facilitate.
