### ISSUE TITLE
does not work from pleroma

### ISSUE THREAD

**Issue by lucajet** [gugray/rss-parrot#20]
accounts created on rss-parrot are not visibile by pleroma instances

**Comment by gugray** [comment]
.

**Comment by patricuspl** [comment]
maybe piggo.space the creator accepts signups and he's willing to accept you in.

**Comment by gugray** [comment]
I'm happy to pursue this if the Pleroma creator reaches out to show interest in working together to track down the issues!

**Comment by ccbikai** [comment]
I can follow parrot https://miantiao.me/@birb@rss-parrot.net on my instance of pleroma but can't see its updates
