### ISSUE TITLE
Some Feeds not Read

### ISSUE THREAD

**Issue by TedTschopp** [gugray/rss-parrot#21]
I use a service out there to translate my Steam Achievements into an RSS feed.  However when I ask the bird to turn this into an account online, the bird can't find anything.  I'm not really all that interested in getting this feed uplifted into Mastodon, however I will say that the feed is valid, however I suspect the server is blocking the bird from reading the RSS feed.   I thought I'd bring it up.  Here is a link to the feed that is clearly a feed, but the bird is blind to.

Feed:  https://truesteamachievements.com/friendfeedrss.aspx?gamerid=90878

**Comment by gugray** [comment]
Thanks for bringing this up! Something in the network between the birb and your server is blocking the request. This is what I'm seeing in the log:

2024-01-09 22:40:24.577 INFO <logic/feed_follower.go:425> Retrieving site information: https://truesteamachievements.com/friendfeedrss.aspx?
2024-01-09 22:40:24.612 WARN <logic/feed_follower.go:191> Failed to get site: request for https://truesteamachievements.com/friendfeedrss.as

Hope that helps.

**Comment by gugray** [comment]
If you find something specific in the birb's request that could change to prevent them from getting rejected, please let me know! For now I'm marking it as not-an-issue.
