### ISSUE TITLE
Parrot account not working with WaterWaysMap.org rss

### ISSUE THREAD

**Issue by watmildon** [gugray/rss-parrot#22]
The birb set up [this account](https://en.osm.town/@amandasaurus.github.io.osm-river-basins@rss-parrot.net) for [waterwaymap.org](https://waterwaymap.org/) but doesn't appear to have noticed/posted the last few updates. Any idea? Any other diagnostic I can provide.

Here's a link into the thread I had with the bot:
https://rss-parrot.net/u/birb/status/1704748268325307221

Many thanks for this lovely idea.

**Comment by gugray** [comment]
Most of the items in the feed have one of these two links:
https://waterwaymap.org
https://amandasaurus.github.io/osm-river-basins

These are meant to be unique per post; the link identifies the different posts.
The two posts showing up in the parrot account are for these two URLs.

Hope that helps!

**Comment by watmildon** [comment]
Thanks for looking at it.

Specifically I was hoping to get the bot to pick up this feed of data update times, which does seem to have separate items: https://pub-02bff1796dd84d2d842f219d10ae945d.r2.dev/2023-04-01/data_updates.xml. Another rss->email service was able to find this and use it successfully. If there's something that needs to be modified on waterways I can always ping the owner over there.

**Comment by gugray** [comment]
The bot is a bit simplistic in that it only toots the first time a new post appears in the feed (a post being something with a unique link pointing to it). Subsequent updates are ignored, roughly to the tune of "I've  seen this post and tooted about it already".

My mental model has been a blog or news feed with posts. There every new post is accessible via its own link. Sometimes an existing post gets edited/updated, and there can be an item about that in the RSS feed, but with the bot I just focused on tooting when a post is first released.

**Comment by watmildon** [comment]
Got it. Totally reasonable. I look forward to using the bot for other more typical things. I appreciate your time.
