### ISSUE TITLE
[Non-mastodon-Interop] Does not work from Mitra

### ISSUE THREAD

**Issue by tallship** [gugray/rss-parrot#25]
### Summary of issue: 

* Created accounts on rss-parrot are not working correctly on [Mitra](https://codeberg.org/silverpill/mitra/src/branch/main/README.md) instances.

* Test machines for [non-mastodon-interop](https://github.com/gugray/rss-parrot/labels/non-mastodon-interop) tweaks are available [HERE](http://demo.fedilist.com/instance?software=mitra).

Thanks :)

.

**Comment by gugray** [comment]
Thanks for the links!

**Comment by gugray** [comment]
I'm looking at this from wizard.casa and I'm getting inconclusive results.

- When I'm trying to mention the birb at my test instance, wizard.casa doesn't recognize it as a mention, and doesn't attempt to talk to my instance.
- When I'm trying to mention the regular birb@rss-parrot.net, the message goes through, and wizard.casa receives the birb's reply all right.
- I can also follow parrot accounts from wizard.casa
- Still waiting to see if toots go through from the parrot to wizard.casa.

Can you provide repro steps for what is not working for you?

**Comment by gugray** [comment]
Toots about new posts do not go over to Mitra. At the time to toot goes out, the birb sees an empty string instance inbox.

Tracing it further back: In the profile info retrieved from Mitra (e.g.: https://wizard.casa/users/parrots_friend), there is no "endpoints" section with a "sharedInbox" value. Mastodon has that, and so far the birb uses this address when sending out toots about new feed posts.

**Comment by gugray** [comment]
I briefly considered opening an issue with a question about the absence of the shared inbox here: https://codeberg.org/silverpill/mitra/issues

But a glance through the issues tells me the project is abandoned (e.g., the second issue from the top is a spam about web monetization, and has been sitting there for 3 weeks).

I'm closing this as "won't fix", but I'll keep in mind the scenario without a shared inbox when tracking down interop issues with other Fediverse platforms. If it comes up again, I'll implement a fallback to deliver toots on a per-user basis.
