### ISSUE TITLE
No response to request from GoToSocial

### ISSUE THREAD

**Issue by kvibber** [gugray/rss-parrot#26]
If I send a message to RSS parrot from a GoToSocial account, I never get a response from the bot.

Logs from the GTS side suggest that RSS Parrot doesn't like the formatting of the request. Messages from GTS to other platforms like Mastodon do work, so I'm guessing it's a parse issue and not a generating issue.

I'll see about getting some more detail logs including what GoToSocial is sending.

```
timestamp="11/01/2024 02:47:13.361" func=federation.(*federatingActor).Send level=INFO requestID=rtj6nxmc04001n481h4g msg="send activity Create via outbox https://gts.keysmash.xyz/users/kelsonv/outbox"
timestamp="11/01/2024 02:47:13.366" func=httpclient.(*Client).DoSigned level=INFO method=POST url=https://rss-parrot.net/inbox requestID=rtj6nxmc04001n481h4g pubKeyID=https://gts.keysmash.xyz/users/kelsonv/main-key msg="performing request"
timestamp="11/01/2024 02:47:13.581" func=workers.(*clientAPI).CreateStatus level=ERROR requestID=rtj6nxmc04001n481h4g msg="error federating status: CreateStatus: error sending Create activity via outbox https://gts.keysmash.xyz/users/kelsonv/outbox: func1: error delivering to https://rss-parrot.net/inbox: deliver: POST request to https://rss-parrot.net/inbox failed: status=\"400 Bad Request\" body=\"{\"error\":\"Request body is not valid JSON\",\"status\":400}\n\""
```

**Comment by gugray** [comment]
Thanks for the useful details! I found the trace of this request in the log. The problem is that my data model treats the "to" and "cc" fields as arrays; that is what I have always seen from Mastodon. In the request from GoToSocial, the "to" field's value is a string.

I'm trying to track this down (not because I want to be "right" but to understand what's going on). So far I cannot find a single document with a formal specification of what is a valid Activity, the acceptable types of each field etc... I've seen this JSON polymorphism elsewhere (in "object") and in all honesty this is driving me crazy.

But, I'll stop whining and return to doing what I did with the Parrot all along: undestand the protocol through good old trial-and-error.

**Comment by kvibber** [comment]
Ugh, I see what you mean. I just spent more time than I should looking through the [vocab doc](https://www.w3.org/TR/activitystreams-vocabulary/) and can't find any indication of whether single-item parameters should be just the items or single-item arrays. Though there are a couple of single-item `"to"` examples buried in a non-normative section, so even if it doesn't *say* so, it at least has an example that matches [GoToSocial's interpretation](https://docs.gotosocial.org/en/latest/federation/federating_with_gotosocial/).

**Comment by gugray** [comment]
Thanks for looking into this too! I didn't mean to say GoToSocial was doing anything wrong; it's just hard to figure out some of the details about ActivityPub. Any case, if to/cc is used either as an array or a string in the wild, that's what the parrot will need to get used to :)

**Comment by gugray** [comment]
Also @kvibber can you give me access to a GoToSocial instance? I don't seem to find any directory, hence also no instance where I could sign up.

**Comment by kvibber** [comment]
@gugray Sorry it took a while to get back to you. Yes, I can set up a test account for you on my test instance, gts.keysmash.xyz. Let me know how I should send you the login info.

**Comment by gugray** [comment]
Sorry, now I've been focusing on other things. Could you do these two things?

1: Check if the problem is still there. I already made parsing this JSON more robust back in January; unless there are other issues too, it should already work!

2: If the problem is there, I'd like an account with the Parrot's email, rss.parrot@gmail.com

Thanks~

**Comment by kvibber** [comment]
Interesting: I'm still not able to follow an RSS-Parrot-generated account from GTS or get a reply from @ birb, but I'm seeing a different error now: 

```
timestamp="23/02/2024 04:47:49.083" func=server.glob..func1.Logger.func13.1 level=INFO latency="271.219µs" userAgent="RSS-Parrot-Bot/0.0.57 (+https://rss-parrot.net)" method=GET statusCode=406 path=/users/kelsonv/main-key clientIP=64.176.202.191 pubKeyID=https://rss-parrot.net/u/birb#main-key errors="Error #01: no format can be offered for requested Accept header(s) [application/json]; this endpoint offers [application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\" application/activity+json text/html]\n" requestID=be0mnn4d04000vfe7ry0 msg="Not Acceptable: wrote 186B"
```

It looks like another case where GoToSocial is [more strictly enforcing the spec](https://docs.gotosocial.org/en/latest/federation/federating_with_gotosocial/) than most AP software. So requesting one of these types should fix that part:
- application/activity+json
- application/activity+json; charset=utf-8
- application/ld+json; profile="https://www.w3.org/ns/activitystreams"

I'll set up that test account for you and send the login info to that email address.

**Comment by kvibber** [comment]
I found another log entry that looks relevant:

```
timestamp="23/02/2024 04:47:21.121" func=dereferencing.(*Dereferencer).enrichAccount level=ERROR requestID=v89mnn4d040017ssgt7g msg="error webfingering[1] remote account birb@rss-parrot.net: fingerRemoteAccount: error webfingering @birb@rss-parrot.net: Finger: non webfinger type response: application/activity+json; charset=utf-8"
```

It took some digging to find what it was expecting, but [apparently webfinger is supposed to](https://datatracker.ietf.org/doc/html/rfc7033#section-4.2) respond with `application/jrd+json`

**Comment by kvibber** [comment]
OK, I've set up the test account and emailed the info to rss.parrot@gmail.com. Let me know if you have any problems connecting to it!

**Comment by gugray** [comment]
Changes from latest commit:
- GTS expects application/jrd+json in Content-Type of webfinger response; rejected application/json
- GTS expects application/activity+json in Content-Type of POST activity calls; rejected application/json
- GTS expects application/activity+json in Accept header of GET requests of user profiles; rejected application/json
- When querying /users/rssparrot/main-key (from HTTP signature), GTS only returns the key, not the rest of the user info. This caused the Parrot to miss a lot of fields. No querying by activity's actor, not key URL from signature.
- GTS puts a single tag as an object in the activity; other systems always use an array here. Now parsing permissively, accepting nothing, a single tag, and an array of tags as well.
- GTS sends Follow and Undo requests to the instance inbox, not the user inbox. It puts the followed/unfollowed user name in the activity's 'to' field. This is exactly the opposite of what Mastodon servers do. Now coping with both.
- GTS does not have a shared inbox. Now sending toots to individual users if they don't have a shared inbox in their profile. (Mastodon servers all have a shared inbox.)

What works now:
- Can request a feed from the birb by sending DM to @birb@rss-parrot. Responses show up in GTS.
- Can follow feed accounts in the Parrot.
- Toots about new posts show up in GTS timeline.

What does not work:
- When I toot in GTS with public, unlisted or followers visibility, the Parrot receives no notification about the mention whatsoever. Therefore it cannot respond the these toots.

**Comment by kvibber** [comment]
Thanks yet again for helping with this!

Interestingly, my own account *is* able to get a reply from birb when mentioning it in a public or unlisted post, so I'm not sure why it didn't work with the test account. Maybe they have different settings.

While I'm at it, I decided to check against Snac2, which is another small-scale ActivityPub server I'm also testing. And it seems to work fine there too.

**Comment by gugray** [comment]
For now I'm inclined to consider this solved! If any anomalies come up, we can deal with those in separate issues.

Thanks for your help and insights in untangling this!
