### ISSUE TITLE
Entities like &#39; showing up in descriptions

### ISSUE THREAD

**Issue by gugray** [gugray/rss-parrot#3]
Quick fix: just unescape the entities which appear to appear frequently

Deep fix: check a lot of retrieved descriptions, see to what extent they have HTML markup, come up with a good-enough approach to sanitize them if needed.

**Comment by charlesroper** [comment]
Example of this issue in a feed generated from YouTube:

https://rss-parrot.net/web/feeds/www.youtube.com.channel.ucb9awk0xfz2p-ny2nsxghra

**Comment by alexjsp** [comment]
Thanks for the fix, I noticed yesterday I wasn't seeing broken characters anymore! 💜
