### ISSUE TITLE
Detect duplicate title and body

### ISSUE THREAD

**Issue by TheLastBoyScoutUK** [gugray/rss-parrot#31]
Some feeds (e.g. those provided by nitter.cz) duplicate the article title and body. Is it possible to detect for this and remove one or the other?

Example:

![Screenshot_20240120-163311-226](https://github.com/gugray/rss-parrot/assets/145464581/28dd7b0b-198f-4062-852a-c034dfb8c015)

**Comment by gugray** [comment]
This is not doable within the scope of RSS Parrot. It needs to stay a small and lean system, and part of that is that it doesn't do any kind of analysis or processing on the feed content. Developing heuristics to detect similar, sort-of-duplicate content within posts, let alone across posts, is beyond the birb's means.

**Comment by TheLastBoyScoutUK** [comment]
Perhaps just an option to take from the feed the `<title>` only and excludes the `<description>`? 

E.g. if it were a cli tool, something like `@birb [feed] --title-only`
