### ISSUE TITLE
Google Alerts Feed does not work

### ISSUE THREAD

**Issue by gwater** [gugray/rss-parrot#35]
The feed `https://www.google.de/alerts/feeds/15238767306718225030/1632617747796897053` gets the response 

"Hm, I can't find a feed for this site.

Is the address right? It can also happen that the site is temporarily down, or it doesn't have a valid RSS or Atom feed."

**Comment by gugray** [comment]
The problem with these feeds is that they don't belong to a website+path: they are just feeds in the void. The name of the account in RSS parrot is derived from the site/page to which the feed belongs. With these Google alert feeds, that doesn't exist.

I didn't anticipate feeds that don't belong to a website. There is no simple solution to this, and for the time being I'm also more inclined to not wanting to fix this. I prefer the parrot to be busy with directly human-generated content; there's something in me that doesn't like parroting entirely machine-generated feeds.
