### ISSUE TITLE
Refresh frequency

### ISSUE THREAD

**Issue by fishcharlie** [gugray/rss-parrot#36]
Curious how often this service polls for updates to the RSS feeds. Didn't see anything mentioned about it in https://rss-parrot.net/web/about.

**Comment by gugray** [comment]
This is a configuration option, but the actual configuration values only exist in the service, not in the public code on Github. The polling frequency depends on how old the last post is.

<1 day: hourly
<1 week: every 3 hours
<4 weeks: every 6 hours
older: every 12 hours
