### ISSUE TITLE
one of my accounts is not receiving updates

### ISSUE THREAD

**Issue by michaldziwisz** [gugray/rss-parrot#51]
Account: www.wirtualnemedia.pl@rss-parrot.net
RSS URL: https://www.wirtualnemedia.pl/rss/wirtualnemedia_rss.xml
The last update on this account was about 2 months ago, meanwhile in the RSS reader the feed refreshes correctly.

**Comment by michaldziwisz** [comment]
For what reason I have no idea, but as of this morning the www.wirtualnemedia.pl@rss-parrot.net account has started sending news again, so it looks like the problem has been resolved.

**Comment by gugray** [comment]
Thanks for reporting! And sorry I haven't been able to investigate sooner. The RSS feed now seems to go back only till Mon, 17 Jun 2024 22:58:00 +0200, so it will be hard to figure out where the discrepancy between the feed reader and the parrot may have come from. I can look back to June 13 in the logs right now, and I'm not seeing any errors related to updating the RSS feed.

Please do report again if you find another anomaly!
